name: Validate Dependency Review Config

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r test/requirements.txt

      - name: Run dependency review YAML validation
        run: python test/test_dependency_review_config.py .github/dependency-review-config.yml
